export enum EMimeTypeEnum {
    JPEG = 'image/jpeg',
    PNG = 'image/png',
    GIF = 'image/gif',
    PDF = 'application/pdf',
    DOC = 'application/msword',
    DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    XLS = 'application/vnd.ms-excel',
    XLSX = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    PPT = 'application/vnd.ms-powerpoint',
    PPTX = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    ZIP = 'application/zip',
    RAR = 'application/x-rar-compressed',
    TXT = 'text/plain',
    CSV = 'text/csv',
    JSON = 'application/json',
    HTML = 'text/html',
    CSS = 'text/css',
    JS = 'application/javascript',
    MP4 = 'video/mp4',
    WEBM = 'video/webm',
    OGG = 'video/ogg',
    MP3 = 'audio/mpeg',
    WAV = 'audio/wav',
    AVI = 'video/x-msvideo',
}
